name: aspiranto
description: "Aspiranto - The Ultimate CAT & Exam Prep OS Flutter Mobile App"
publish_to: 'none'
version: 1.0.26+10026

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.14.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
